-- Superseded: notification INSERT/DELETE + linter fixes live in
-- `fix_supabase_linter.sql` (run that on existing projects).
--
-- For a DB that only had the old permissive INSERT, run `fix_supabase_linter.sql`
-- which DROPs "Authenticated users can insert notifications" and creates
-- "Users can insert gig-linked notifications".
